#!/usr/bin/env bash
# Usage: meg ssh <host> [command...]
# Summary: SSH into a RubyGems.org server.
# Help: This can be combined with more commands, for example:
#
#    meg ssh app01 ls -lah
set -e

HOST=$1
shift

exec ssh -t -C $HOST "$@"
