#!/usr/bin/env bash
# Usage: meg ssh [command...]
# Summary: SSH into the RubyGems.org app server.
# Help: This can be combined with more commands, for example:
#
#    meg ssh ls -lah
set -e

exec ssh -t -C app02.production.rubygems.org "$@"
