#!/usr/bin/env bash
# Usage: meg maint-off
# Summary: Disable maintenance mode
# Help: SSH to load balancer and remove the maintenance symlink

set -e

exec meg-ssh $MEG_BALANCER_HOST "sudo rm /var/www/rubygems/maintenance.html"