#!/usr/bin/env bash
# Usage: meg console
# Summary: Fire up a Rails console remotely
# Help: SSH directly into a Rails console for RubyGems.org

set -e

exec meg-ssh "cd /applications/rubygems/current && sudo /usr/bin/chpst -u deploy:deploy -e /etc/sv/unicorn/env /usr/local/bin/bundle exec rails console"
