#!/usr/bin/env bash
# Usage: meg maint-on
# Summary: Enable maintenance mode
# Help: SSH to balancer02 and add the maintenance symlink

set -e

exec ssh -t -C $USER@54.245.255.174 "sudo ln -s /opt/nginx/conf/maintenance.html /opt/nginx/html/maintenance.html"