#!/usr/bin/env bash
# Usage: meg maint-off
# Summary: Disable maintenance mode
# Help: SSH to load balancer and remove the maintenance symlink

set -e

exec ssh -t -C $USER@rubygems.org "sudo rm /opt/nginx/html/maintenance.html"