#!/usr/bin/env bash
# Usage: meg maint-on
# Summary: Enable maintenance mode
# Help: SSH to load balancer and add the maintenance symlink

set -e

exec meg-ssh $MEG_BALANCER_HOST "sudo ln -s /etc/nginx/maintenance.html /var/www/rubygems/maintenance.html"