#!/usr/bin/env bash
# Usage: meg maint-on
# Summary: Enable maintenance mode
# Help: SSH to load balancer and add the maintenance symlink

set -e

exec ssh -t -C $USER@rubygems.org "sudo ln -s /opt/nginx/conf/maintenance.html /opt/nginx/html/maintenance.html"