#!/usr/bin/env bash
# Usage: meg script
# Summary: Run a script inside the RubyGems.org Rails directory
# Help: SSH directly RubyGems.org and run a script

set -e

exec meg-ssh "cd /applications/rubygems/current && sudo -u deploy ./script/$@"
